export const COM_OPEN_REPO = 'saber2pr.open.repo'
export const COM_OPEN_TERMINAL = 'saber2pr.open.terminal'
export const COM_CHANGE_THEME = 'saber2pr.change.theme'
export const COM_CHANGE_LOCALE = 'saber2pr.change.locale'
export const COM_RELOAD = 'saber2pr.reload'
export const COM_OPEN_VSC_MARKETPLACE = 'saber2pr.open.vsc-marketplace'
